-- point_record.request_id 固定为二进制排序规则（V2 第 5 批评审第 3 / 5 / 6 轮）。
--
-- 原属 V33，第 6 轮拆出来单独成版：那个文件里它是第 2 条语句，而第 1 条会先成功并隐式提交，
-- 于是本条一旦失败，整个 V33 就成了「做了一半、又无法重跑」的死局（详见 V33 抬头）。
-- **一个迁移文件只放一条有失败可能的语句**，失败即「什么都没发生」。
--
-- ────────────────────────────────────────────────────────────────────────────
-- 背景：申诉成立要写一笔反向流水，幂等键是 `sys:rp-revert:{奖惩单 id}`（PointSourceType）。
--   PointService 用「前缀是系统保留」挡住手工调整来抢占这个键。
--
-- 缺陷：V24 建表时 request_id 只写了 VARCHAR(64)，跟随表级 utf8mb4 的**服务器默认排序规则**，
--   MySQL 8 下即 utf8mb4_0900_ai_ci —— ai = accent insensitive、ci = case insensitive。
--   于是 uk_request_id 认为 'sýs:rp-revert:1' 与 'sys:rp-revert:1' 是同一个键，
--   而 Java 侧的前缀守卫（哪怕忽略大小写）认为它们不同：手工调整传 'sýs:rp-revert:1'
--   过得了守卫、却占住那张单的冲正位。此后那张单一旦申诉成立，反向流水会撞上这条已存在的键，
--   PointService 复核载荷发现不是同一笔（来源码 5 vs 6）→ 抛「积分入账冲突」→
--   **整个受理事务回滚**：处置没解除、分没退、申诉也办不下去，直到有人手工清掉那条占位流水。
--   （早先注释写成「静默跳过、处置解除了分退不回来」是错的：载荷复核会拦下来，
--     失败是响亮的，只是把一次申诉受理彻底卡死。）
--
-- 修法：让「数据库眼里的相等」与「Java 眼里的相等」重合，而不是在 Java 里追着枚举
--   排序规则的等价类（重音、全半角、变体选择符…… 那是列不完的）。
--
-- 【必须是 utf8mb4_0900_bin，不能用 utf8mb4_bin】两者都按码点比较，但
--   utf8mb4_bin 的 PAD_ATTRIBUTE 是 **PAD SPACE**——比较时忽略尾部空格，
--   于是 'k' 与 'k ' 仍被视为同一个键。那正好是本迁移要消除的那类「库比 Java 宽」，
--   换过去等于把重音的洞换成尾空格的洞（而 0900_ai_ci 本身是 NO PAD，反倒没有这个洞，
--   选错排序规则会是一次**倒退**）。utf8mb4_0900_bin 是 NO PAD，尾空格参与比较，
--   这才真正与 String.equals 一致。V34RequestIdCollationTest 直接断言 NO PAD。
--
-- 🛑 【本条决定了项目的最低数据库版本 = MySQL 8.0.17】
--   utf8mb4_0900_bin 是 **8.0.17 新增**的排序规则；8.0.16 上执行本条会得到
--   `ERROR 1273 (HY000): Unknown collation: 'utf8mb4_0900_bin'`（已在 mysql:8.0.16 容器实测）。
--   CHECK 约束的 8.0.16 门槛更低，所以两者取大：**8.0.17**。
--   启动时由 DatabaseVersionGuard 在 **Flyway 迁移之前**校验——放在迁移之后只能让实例起不来，
--   拦不住已经执行过的半截迁移。
--
-- 安全性：从不敏感排序规则改到二进制只会**拆分**等价类、不会合并，
--   原本能共存的行改完仍然互不相等，uk_request_id 不可能因此冲突，无需先清理数据。
--   保留 utf8mb4 字符集（而非改 ascii）：改字符集会在存量含非 ASCII 值时直接失败，
--   而本迁移不该有失败的可能。
--
-- 注意：本 ALTER 会重建 uk_request_id，大表上需要停机窗口。point_record 目前量级很小；
--   将来若已很大，请改用 pt-online-schema-change / gh-ost 等在线方案执行同一变更。
ALTER TABLE point_record
    MODIFY COLUMN request_id VARCHAR(64) COLLATE utf8mb4_0900_bin DEFAULT NULL
        COMMENT '幂等键（手工调整必填，由前端每次生成；其余来源为 NULL）。二进制 + NO PAD：与 Java 的字符串相等一致，见 V34';
